"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Bot, Database, RefreshCw, Signal } from "lucide-react";
import { ReporterChat } from "@/components/reporter/reporter-chat";
import { formatRelativeTime } from "@/lib/utils";

interface ReporterRecord {
  id: string;
  recordType: string;
  title: string;
  status: string;
  updatedAt: string;
}

export default function ReporterPage() {
  const [reports, setReports] = useState<ReporterRecord[]>([]);
  const [openSignals, setOpenSignals] = useState(0);
  const [scanning, setScanning] = useState(false);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    try {
      const [recordsRes, signalsRes] = await Promise.all([
        fetch("/api/modules/reporter-agent/records?limit=10"),
        fetch("/api/modules/signals?status=open&limit=1"),
      ]);
      if (recordsRes.ok) {
        const body = await recordsRes.json();
        setReports(body.data || []);
      }
      if (signalsRes.ok) {
        const body = await signalsRes.json();
        setOpenSignals(body.pagination?.total ?? 0);
      }
    } catch {
      // panel data is non-critical
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  async function runScan() {
    setScanning(true);
    setError("");
    try {
      const res = await fetch("/api/modules/reporter-agent/scan", { method: "POST" });
      const body = await res.json();
      if (!res.ok) throw new Error(body?.error?.message || body?.error || "Scan failed");
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Scan failed");
    } finally {
      setScanning(false);
    }
  }

  return (
    <div className="h-full overflow-y-auto bg-owly-bg">
      <div className="mx-auto grid h-full max-w-[1400px] gap-5 p-5 xl:grid-cols-[minmax(0,1fr)_380px]">
        <section className="flex min-h-[70vh] flex-col overflow-hidden rounded-xl border border-owly-border bg-owly-surface">
          <div className="flex items-center justify-between border-b border-owly-border px-5 py-4">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-owly-primary-50 text-owly-primary">
                <Bot className="h-5 w-5" />
              </div>
              <div>
                <h1 className="text-lg font-bold text-owly-text">Reporter Agent</h1>
                <p className="text-sm text-owly-text-light">
                  Ask about anything in your modules. Answers cite the records they come from.
                </p>
              </div>
            </div>
          </div>
          <div className="min-h-0 flex-1">
            <ReporterChat />
          </div>
        </section>

        <aside className="space-y-5">
          <section className="rounded-xl border border-owly-border bg-owly-surface p-5">
            <div className="flex items-center justify-between">
              <h2 className="font-semibold text-owly-text">Monitoring</h2>
              <button
                type="button"
                disabled={scanning}
                onClick={runScan}
                className="inline-flex items-center gap-2 rounded-lg border border-purple-200 bg-purple-50 px-3 py-1.5 text-sm font-semibold text-purple-700 hover:bg-purple-100 disabled:opacity-60"
              >
                <RefreshCw className={scanning ? "h-4 w-4 animate-spin" : "h-4 w-4"} />
                {scanning ? "Scanning..." : "Run scan"}
              </button>
            </div>
            {error && <p className="mt-2 text-sm text-red-600">{error}</p>}
            <div className="mt-4 flex items-center justify-between rounded-lg bg-owly-bg p-3">
              <span className="flex items-center gap-2 text-sm text-owly-text">
                <Signal className="h-4 w-4 text-purple-600" />
                Open signals
              </span>
              <span className="text-lg font-bold text-owly-text">{openSignals}</span>
            </div>
            <Link
              href="/modules/reporter-agent"
              className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-owly-primary hover:underline"
            >
              <Database className="h-4 w-4" />
              Open Reporter workspace
            </Link>
          </section>

          <section className="rounded-xl border border-owly-border bg-owly-surface">
            <div className="border-b border-owly-border px-5 py-4">
              <h2 className="font-semibold text-owly-text">Recent reports</h2>
              <p className="text-sm text-owly-text-light">Generated by scans and the heartbeat.</p>
            </div>
            {reports.length === 0 ? (
              <p className="px-5 py-8 text-center text-sm text-owly-text-light">No reports yet. Run a scan.</p>
            ) : (
              <div className="divide-y divide-owly-border">
                {reports.map((report) => (
                  <Link
                    key={report.id}
                    href={`/modules/reporter-agent/records/${report.id}`}
                    className="block px-5 py-3 hover:bg-owly-bg/60"
                  >
                    <p className="truncate text-sm font-semibold text-owly-text">{report.title}</p>
                    <p className="mt-0.5 text-xs text-owly-text-light">
                      {report.recordType} - {formatRelativeTime(report.updatedAt)}
                    </p>
                  </Link>
                ))}
              </div>
            )}
          </section>
        </aside>
      </div>
    </div>
  );
}
