"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Bot, Settings as SettingsIcon } from "lucide-react";
import { ReporterChat } from "@/components/reporter/reporter-chat";
import { formatRelativeTime } from "@/lib/utils";

interface ReporterRecord {
  id: string;
  recordType: string;
  title: string;
  status: string;
  updatedAt: string;
}

export default function ReporterPage() {
  const [reports, setReports] = useState<ReporterRecord[]>([]);
  const [isAdmin, setIsAdmin] = useState(false);

  const load = useCallback(async () => {
    try {
      const [recordsRes, meRes] = await Promise.all([
        fetch("/api/modules/reporter-agent/records?limit=10"),
        fetch("/api/auth"),
      ]);
      if (recordsRes.ok) {
        const body = await recordsRes.json();
        setReports(body.data || []);
      }
      if (meRes.ok) {
        const body = await meRes.json();
        setIsAdmin(body.user?.role === "admin");
      }
    } catch {
      // panel data is non-critical
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  return (
    <div className="h-full overflow-hidden bg-owly-bg">
      <div className="mx-auto grid h-full max-w-[1400px] gap-5 p-5 xl:grid-cols-[minmax(0,1fr)_380px]">
        <section className="flex min-h-0 flex-col overflow-hidden rounded-xl border border-owly-border bg-owly-surface">
          <div className="flex items-center justify-between border-b border-owly-border px-5 py-4">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-owly-primary-50 text-owly-primary">
                <Bot className="h-5 w-5" />
              </div>
              <div>
                <h1 className="text-lg font-bold text-owly-text">Reporter Agent</h1>
                <p className="text-sm text-owly-text-light">
                  Ask about anything in your modules. Answers cite the records they come from.
                </p>
              </div>
            </div>
          </div>
          <div className="min-h-0 flex-1">
            <ReporterChat />
          </div>
        </section>

        <aside className="min-h-0 space-y-5 overflow-y-auto">
          {isAdmin && (
            <Link
              href="/settings?tab=reporter"
              className="flex items-center gap-2 rounded-xl border border-owly-border bg-owly-surface px-5 py-3 text-sm font-semibold text-owly-primary hover:bg-owly-bg"
            >
              <SettingsIcon className="h-4 w-4" />
              Monitoring, scans, and heartbeat settings moved to Settings
            </Link>
          )}

          <section className="rounded-xl border border-owly-border bg-owly-surface">
            <div className="border-b border-owly-border px-5 py-4">
              <h2 className="font-semibold text-owly-text">Recent reports</h2>
              <p className="text-sm text-owly-text-light">Generated by scans and the heartbeat.</p>
            </div>
            {reports.length === 0 ? (
              <p className="px-5 py-8 text-center text-sm text-owly-text-light">No reports yet.</p>
            ) : (
              <div className="divide-y divide-owly-border">
                {reports.map((report) => (
                  <Link
                    key={report.id}
                    href={`/modules/reporter-agent/records/${report.id}`}
                    className="block px-5 py-3 hover:bg-owly-bg/60"
                  >
                    <p className="truncate text-sm font-semibold text-owly-text">{report.title}</p>
                    <p className="mt-0.5 text-xs text-owly-text-light">
                      {report.recordType} - {formatRelativeTime(report.updatedAt)}
                    </p>
                  </Link>
                ))}
              </div>
            )}
          </section>
        </aside>
      </div>
    </div>
  );
}
